### ISSUE TITLE
.EXE closing

### ISSUE THREAD

**Issue by Rafaviau** [green-new/find-fortress#1]
when i type the seed and the other information the program run for a sec and then it close itself

**Comment by green-new** [comment]
Hi @Rafaviau

The program actually creates a file called out.txt (in the same directory the program is located) that shows all the fortresses nearby. If you wish to keep the program opened when it runs, open it using Command Prompt:

1. Shift + right click an empty area in the folder where the program is in (FindWitherSkeletonFarm.exe).
2. Click 'Open PowerShell window here'.
3. The powershell.exe window opens.
4. Type 'cmd'. Press enter.
5. Type 'FindWitherSkeletonFarm.exe'. The program will run like normal.
